### PR TITLE
Small fixes related to .NET resource handling.

### PR DESCRIPTION
**Pull request by snemes**
https://github.com/crackinglandia/pype32/issues/8#issuecomment-113225099

### CODE REVIEW

**Comment by snemes** [comment]
https://github.com/crackinglandia/pype32/issues/9#issuecomment-113255839

**Comment by snemes** [comment]
Squashed commits into one.

**Comment by snemes** [comment]
Added fix mentioned in https://github.com/crackinglandia/pype32/issues/8#issuecomment-113902957

**Comment by poxyran** [comment]
Thanks Sandor!

**Pull request merged**
